# Generated by Django 2.2.5 on 2019-09-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_date',
            new_name='date',
        ),
    ]
